# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'EveryMap' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for EveryMap
  pod 'KakaoMapsSDK', '2.6.0'
  pod 'NMapsMap'

end
